- name: создаем пользователя awx на cisco девайсах
  hosts: manufacturers_cisco
  gather_facts: no
  connection: network_cli
  vars:
    ansible_network_os: ios 
    new_username: awx
    new_password: Ghjrhecn22
  tasks:
    - name: config cisco
      ansible.netcommon.cli_command:
        commands:
          - conf t
          - username {{ new_username }} privilege 15 secret 0 {{ new_password }}
          - end
    - name: Save configuration
      ansible.netcommon.cli_command:
        commands:
          - wr
