---
- name: Создание пользователя на Cisco IOS
  hosts: manufacturers_cisco
  connection: network_cli
  gather_facts: false

  collections:
    - cisco.ios

  vars:
    ansible_network_os: cisco.ios
    ansible_network_cli_ssh_type: paramiko
    new_username: awx
    new_password: Ghjrhecn22
    new_privilege: 15

  tasks:
    - name: Create or update local user
      cisco.ios.ios_user:
        name: "{{ new_username }}"
        privilege: "{{ new_privilege }}"
        configured_password: "{{ new_password }}"
        update_password: always
        state: present

    - name: Save running config to startup
      cisco.ios.ios_config:
        save_when: always
