---
- name: Создание пользователя awx на Maipu
  hosts: manufacturers_maipu
  gather_facts: false
  connection: ansible.netcommon.network_cli
  serial: 10

  vars:
    ansible_network_os: community.network.maipu
    ansible_network_cli_ssh_type: paramiko
    new_username: awx
    new_password: Ghjrhecn22
    maipu_regular_commands:
      - conf t
      - local-user {{ new_username }} class manager
      - service-type telnet console ssh ftp web netconf
      - privilege 15
      - password 0 {{ new_password }}
      - end
    maipu_wnc6600_commands:
      - conf t
      - user {{ new_username }} privilege 15 password 0 {{ new_password }}
      - end

  tasks:
    - name: Показать модель устройства (из NetBox)
      debug:
        msg: "Устройство {{ inventory_hostname }} модель {{ device_model | default('unknown') }}"
    - name: Configure standard Maipu devices
      community.network.maipu_command:
        commands: "{{ maipu_regular_commands }}"
      when: device_model | default('') != "WNC6600-100-AC(V1)"
      register: maipu_result
    - name: Configure WNC6600 devices
      community.network.maipu_command:
        commands: "{{ maipu_wnc6600_commands }}"
      when: device_model | default('') == "WNC6600-100-AC(V1)"
      register: maipu_result
    - name: Save configuration
      community.network.maipu_command:
        commands:
          - write memory
      when: maipu_result is succeeded
    - name: Show execution result
      debug:
        var: maipu_result.stdout_lines
